### ISSUE TITLE
[REQUEST] Storngly signed version

### ISSUE THREAD

**Issue by kirillkovalenko** [TBCBank/TBC.Common.Configuration.Registry#33]
It would nice if you provide a version with a strong name.

```
CS8002: Referenced assembly 'TBC.Common.Configuration.Registry, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
```

**Comment by 0xfeeddeadbeef** [comment]
@kirillkovalenko Strongly named version has been released: [![NuGet Version](https://img.shields.io/nuget/v/TBC.Common.Configuration.Registry?link=https%3A%2F%2Fwww.nuget.org%2Fpackages%2FTBC.Common.Configuration.Registry%2F2.0.1%2F)](https://www.nuget.org/packages/TBC.Common.Configuration.Registry/2.0.1/)
